apiVersion: v1
kind: Service
metadata:
  name: getting-started-with-octopus
  namespace: "#{Kubernetes.Namespace}"
spec:
  type: LoadBalancer
  selector:
    app: getting-started-with-octopus
  ports:
    - port: 80
      targetPort: 3000
